config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'
  get 'tasks/show'
  get 'tasks/new'
  get 'tasks/create'
  get 'tasks/edit'
  get 'tasks/update'
  get 'tasks/detroy'
  get 'projects/index'
  get 'projects/show'
  get 'projects/create'
  get 'projects/update'
  get 'projects/detroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  #les ressouces taks sont imbriqués dans project pour indiquer que les taches sont liées à des projets specifiques
  resources :projects do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    #has_many pour indiquer que le projet peut avoir plusieurs taches, 
    #dependent: :destroy pour que les taches associées soient supprimées si le projet est supprimé
    has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  #belong_to pour iniquer qu'une tahce appartient à un projet
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
       redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully deleted.'
  end


  private

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project ##appel de la fonction uqi sera éxécuté avant les actions qui suivent, pour s'assurer que le projet est correctement recupéré

  def index
    @tasks = @project.tasks
  end

  def show
    @task = @project.tasks.find(params[:id])
  end

  def new
    @task = @project.tasks.build
  end

  def create
    @task = @project.tasks.build(task_params)
    if @task.save
      redirect_to [@project, @task]
    else
      render :new
    end
  end

  def edit
    @task = @project.tasks.find(params[:id])
  end

  def update
    @task = @project.tasks.find(params[:id])
    if @task.update(task_params)
       redirect_to [@project, @task]
    else
      render :edit
    end
  end

  def destroy
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to project_tasks_path(@project)
  end

  private

  #Methode qui sert à recupere le projet auquel la tache est associé
  def set_project
    @project = Project.find(params[:project_id])# on met dans @project le contenu de la recherche, ce qui correspond au poject id afin d'appeler la fonction tout en haut
  end

  #Methode utilisé pour filtrer et securiser les parametre des la requete http avant de creer ou de mettre à jour une route
  #En Rails, cela est necessaire pour éviter les problemes de securité tels que l'attaque des masse d'affectation
  def task_params
    params.require(:task).permit(:title, :description, :status, :due_date)# les autre parametre de la requete seront ignorés si pas passé
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagerAPp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <script src="<%= asset_path 'rails-ujs.js' %>"></script>
  </head>

  <body>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/detroy.html.erb
<h1>Projects#detroy</h1>
<p>Find me in app/views/projects/detroy.html.erb</p>

app/views/projects/edit.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-md8 offset-md-2">
            <h1>Edit Project</h1>

            <%= form_with(model: @project, local:true) do |form| %>
            <% if @project.errors.any? %>
                <div id="error_explanation" class="alert-danger">
                    <h4><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h4>

                    <ul>
                        <% @project.erros.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="from-group">
                <%= form.label :title %>
                <%= form.text_field :title, class: 'form-control' %>
            </div>

            <div class="from-group">
                <%= form.label :description %>
                <%= form.text_area :description, class: 'form-control' %>
            </div>

            <div class="fomr-group mt-3">
                <%= form.submit "Upgrade Project", class: 'btn btn-primary' %>
                <%= link_to 'back to Projects', projects_path(@project), class: 'btn btn-link' %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/projects/index.html.erb
<div class="container mt-5">
    <h1>Projects</h1>

    <%= link_to 'New Project', new_project_path %>

    <% if @projects.any? %>

    <ul class="list-group">
        <% @projects.each do |project| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <span>
                    <%= link_to project.title, project_path(project) %>
                </span>
                <span>
                    <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-secondary btn-sm' %>
                    <%= link_to 'Delete', project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
                </span>
            </li>
        <% end %>
    </ul>
    <% else %>
        <p>No projects found. Add a new project to get started!</p>
    <% end %>
</div>

app/views/projects/new.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
        <h1>New Project</h1>

        <%= form_with(model: @project, local:true) do |form| %>
        <% if @project.errors.any? %>
            <div id="error_explanation" class="alert-danger">
                <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

                <ul>
                    <% @project.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group mt-3">
            <%= form.submit "Create Project", class: 'btn btn-primary' %>
            <%= link_to 'back to Projects', projects_path(@project), class: 'btn btn-link' %>
        </div>
        <% end %>
        </div>
    </div>
</div>

app/views/projects/show.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-md8 offset-md-2">
        <h1><%= @project.title %></h1>

        <div class="car mb-4">
            <div class="card-body">
            <h5 class="card-title">Description</h5>
            <p class="card-text"><%= @project.description %></p>
        </div>

        <h2>Tasks</h2>

        <%= link_to 'New Task', new_project_task_path(@project), class: 'btn btn-primary mb-3' %>

        <% if @project.tasks.any?%>
        <ul class="list-group-mb-4">
            <% @project.tasks.each do |task| %>
                <li class="list-group-item d-flex justify-content-between align-item-center">
                    <span>
                        <%= link_to task.title, project_task_path(@project, task) %>
                    </span>
                    <span>
                        <%= link_to 'Edit', edit_project_task_path(@project, task), class: 'btn btn-secondary btn-sm' %>
                        <%= link_to 'Delete', project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
                    </span>
                </li>
            <% end %>
        </ul>
        <% else %>
            <p class="alert alert-info">No tasks found for this project. Add a new task to get started/</p>
        <% end %>

        <div class="mt-4">
            <%= link_to 'Edit Project', edit_project_path(@project), class: 'btn btn-secondary' %> |
            <%= link_to 'Delete Project', projects_path(@project), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger' %> |
            <%= link_to 'Back to Projects', projects_path, class: 'btn btn-link' %>
        </div>
        </div>
    </div>
</div>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/detroy.html.erb
<h1>Tasks#detroy</h1>
<p>Find me in app/views/tasks/detroy.html.erb</p>

app/views/tasks/edit.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
        <h1>Edit Task</h1>

        <%= form_with(model: [@project, @task], local:true) do |form| %>
        <% if @task.errors.any? %>
            <div id="error_explanation" class="alert-danger">
                <h4 class= "alert-heading"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

                <ul>
                    <% @task.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= form.label :status %>
            <%= form.text_field :status, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= form.label :due_date %>
            <%= form.date_field :due_date, class: 'form-control' %>
        </div>

        <div class="form-group mt-3">
            <%= form.submit "Update Task", class: 'btn btn-primary' %>
            <%= link_to 'Back to Tasks', project_tasks_path(@project, @task), class: 'btn btn-link' %>
        </div>
        <% end %>
        </div>
    </div>
</div>

app/views/tasks/index.html.erb
<div class="container mt-5">
    <h1>Tasks for <%= @project.title %></h1>

    <%= link_to 'New Task', new_project_task_path(@project), class: 'btn btn-primary mb-3' %>

    <% if @tasks.any?%>
    <ul class="list-group">
        <% @tasks.each do |task| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <span>
                    <%= link_to task.title, project_task_path(@project, task) %>
                </span>
                <span>
                <%= link_to 'Edit', edit_project_task_path(@project, task), class: 'btn btn-secondary btn-sm' %>
                <%= link_to 'Delete', project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
                </span>
            </li>
        <% end %>
    </ul>
    <% else%>
        <p class="alert alert-info">No ptasks found for this project. Add a new task to get started!</p>
    <% end %>

    <%= link_to 'Back to Projects', projects_path(@project), class: 'btn btn-link mt-3' %>
</div>

app/views/tasks/new.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
        <h1>New Task</h1>

        <%= form_with(model: [@project, @task], local:true) do |form| %>
        <% if @task.errors.any? %>
            <div id="error_explanation" class="alert-danger">
                <h4 class= "alert-heading"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

                <ul>
                    <% @task.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= form.label :status %>
            <%= form.text_field :status, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= form.label :due_date %>
            <%= form.date_field :due_date, class: 'form-control' %>
        </div>

        <div class="form-group mt-3">
            <%= form.submit "Create Task", class: 'btn btn-primary' %>
            <%= link_to 'Back to Tasks', project_tasks_path(@project), class: 'btn btn-link' %>
        </div>
        <% end %>
        </div>
    </div>
</div>

app/views/tasks/show.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-md8 offset-md-2">
        <h1><%= @task.title %></h1>

        <div class="car mb-4">
            <div class="card-body">
            <h5 class="card-title">Description</h5>
            <p class="card-text"><%= @task.description %></p>

            <h5 class="card-title">Status</h5>
            <p class="card-text"><%= @task.status %></p>

            <h5 class="card-title">Due Date</h5>
            <p class="card-text"><%= @task.due_date %></p>
        </div>

        <h2>Tasks</h2>

        <%= link_to 'New Task', new_project_task_path(@project), class: 'btn btn-primary mb-3' %>

        

        <div class="mt-4">
            <%= link_to 'Edit Task', edit_project_task_path(@project, @task), class: 'btn btn-secondary' %> |
            <%= link_to 'Delete Task', project_task_path(@project, @task), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger' %> |
            <%= link_to 'Back to tasks', project_tasks_path, class: 'btn btn-link' %>
        </div>
        </div>
    </div>
</div>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>